scan_timeout = 30

"$schema" = 'https://starship.rs/config-schema.json'

[aws]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cpp]
disabled = true

[cmake]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[directory]
read_only = " 󰌾"

[docker_context]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[fennel]
disabled = true

[fortran]
disabled = true

[fossil_branch]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = " "

[git_commit]
disabled = true

[golang]
symbol = " "

[gradle]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[hg_branch]
disabled = true

[hostname]
ssh_symbol = " "

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
symbol = " "

[ocaml]
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
disabled = true

[pixi]
disabled = true

[python]
symbol = " "

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
symbol = "󱘗 "

[scala]
disabled = true

[status]
symbol = " "

[swift]
disabled = true

[xmake]
disabled = true

[zig]
disabled = true
